name: Publish NPM package

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn prepare
      - name: Publish package
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: yarn publish --access public --//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
